#!/bin/bash

ROOT="$(git rev-parse --show-toplevel)"
if [ -z "$ROOT" ]; then exit 1; fi

echo '{
    "env": {
        "browser": true,
        "es2021": true
    },
    "extends": [
        "trybe-frontend",
        "plugin:react/recommended"
    ],
    "parserOptions": {
        "ecmaFeatures": {
            "jsx": true
        },
        "ecmaVersion": 12,
        "sourceType": "module"
    },
    "plugins": [
        "react"
    ],
    "rules": {
    }
}' > "$ROOT/.eslintrc.json"

npm install eslint-config-trybe-frontend eslint-plugin-sonarjs eslint-plugin-react eslint

lint='\"lint\": \"eslint --no-inline-config --no-error-on-unmatched-pattern -c .eslintrc.json . --ext .js, .jsx\"'
package='$ROOT/package.json'

sed -Ei "s/(\"scripts\": {(\n.+?,)+\n(\s+).+)/\1,\n\3${lint}/" ${package}
